<?php 


// Register Custom Post Type
function portfolio_post_type() {

	$labels = array(
		'name'                  => _x( 'Portfolio Items', 'Post Type General Name', 'tabut-companion' ),
		'singular_name'         => _x( 'Portfolio', 'Post Type Singular Name', 'tabut-companion' ),
		'menu_name'             => __( 'Portfolio', 'tabut-companion' ),
		'name_admin_bar'        => __( 'Portfolio', 'tabut-companion' ),
		'archives'              => __( 'Item Archives', 'tabut-companion' ),
		'attributes'            => __( 'Item Attributes', 'tabut-companion' ),
		'parent_item_colon'     => __( 'Parent Item:', 'tabut-companion' ),
		'all_items'             => __( 'All Items', 'tabut-companion' ),
		'add_new_item'          => __( 'Add New Item', 'tabut-companion' ),
		'add_new'               => __( 'Add New', 'tabut-companion' ),
		'new_item'              => __( 'New Item', 'tabut-companion' ),
		'edit_item'             => __( 'Edit Item', 'tabut-companion' ),
		'update_item'           => __( 'Update Item', 'tabut-companion' ),
		'view_item'             => __( 'View Item', 'tabut-companion' ),
		'view_items'            => __( 'View Items', 'tabut-companion' ),
		'search_items'          => __( 'Search Item', 'tabut-companion' ),
		'not_found'             => __( 'Not found', 'tabut-companion' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'tabut-companion' ),
		'featured_image'        => __( 'Product Image', 'tabut-companion' ),
		'set_featured_image'    => __( 'Set Product Image', 'tabut-companion' ),
		'remove_featured_image' => __( 'Remove Product Image', 'tabut-companion' ),
		'use_featured_image'    => __( 'Use as Product Image', 'tabut-companion' ),
		'insert_into_item'      => __( 'Insert into item', 'tabut-companion' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'tabut-companion' ),
		'items_list'            => __( 'Portfolio list', 'tabut-companion' ),
		'items_list_navigation' => __( 'Items list navigation', 'tabut-companion' ),
		'filter_items_list'     => __( 'Filter items list', 'tabut-companion' ),
	);
	$args = array(
		'label'                 => __( 'Portfolio', 'tabut-companion' ),
		'description'           => __( 'Custom Post Type for Portfolio Section', 'tabut-companion' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'thumbnail', 'custom-fields' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-feedback',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'show_in_rest'          => true,
	);
	register_post_type( 'portfolio', $args );

}
add_action( 'init', 'portfolio_post_type', 0 );

/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
class Rational_Meta_Box {
	private $screens = array(
		'portfolio',
	);
	private $fields = array(
		array(
			'id' => 'add_date',
			'label' => 'Add Date',
			'type' => 'date',
		),
		array(
			'id' => 'add_link',
			'label' => 'Add Link',
			'type' => 'url',
		),
	);

	/**
	 * Class construct method. Adds actions to their respective WordPress hooks.
	 */
	public function __construct() {
		add_action( 'add_meta_boxes', array( $this, 'add_meta_boxes' ) );
		add_action( 'save_post', array( $this, 'save_post' ) );
	}

	/**
	 * Hooks into WordPress' add_meta_boxes function.
	 * Goes through screens (post types) and adds the meta box.
	 */
	public function add_meta_boxes() {
		foreach ( $this->screens as $screen ) {
			add_meta_box(
				'product-information',
				__( 'Product Information', 'tabut-companion' ),
				array( $this, 'add_meta_box_callback' ),
				$screen,
				'advanced',
				'default'
			);
		}
	}

	/**
	 * Generates the HTML for the meta box
	 * 
	 * @param object $post WordPress post object
	 */
	public function add_meta_box_callback( $post ) {
		wp_nonce_field( 'product_information_data', 'product_information_nonce' );
		$this->generate_fields( $post );
	}

	/**
	 * Generates the field's HTML for the meta box.
	 */
	public function generate_fields( $post ) {
		$output = '';
		foreach ( $this->fields as $field ) {
			$label = '<label for="' . $field['id'] . '">' . $field['label'] . '</label>';
			$db_value = get_post_meta( $post->ID, 'product_information_' . $field['id'], true );
			switch ( $field['type'] ) {
				default:
					$input = sprintf(
						'<input %s id="%s" name="%s" type="%s" value="%s">',
						$field['type'] !== 'color' ? 'class="regular-text"' : '',
						$field['id'],
						$field['id'],
						$field['type'],
						$db_value
					);
			}
			$output .= $this->row_format( $label, $input );
		}
		echo '<table class="form-table"><tbody>' . $output . '</tbody></table>';
	}

	/**
	 * Generates the HTML for table rows.
	 */
	public function row_format( $label, $input ) {
		return sprintf(
			'<tr><th scope="row">%s</th><td>%s</td></tr>',
			$label,
			$input
		);
	}
	/**
	 * Hooks into WordPress' save_post function
	 */
	public function save_post( $post_id ) {
		if ( ! isset( $_POST['product_information_nonce'] ) )
			return $post_id;

		$nonce = $_POST['product_information_nonce'];
		if ( !wp_verify_nonce( $nonce, 'product_information_data' ) )
			return $post_id;

		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE )
			return $post_id;

		foreach ( $this->fields as $field ) {
			if ( isset( $_POST[ $field['id'] ] ) ) {
				switch ( $field['type'] ) {
					case 'email':
						$_POST[ $field['id'] ] = sanitize_email( $_POST[ $field['id'] ] );
						break;
					case 'text':
						$_POST[ $field['id'] ] = sanitize_text_field( $_POST[ $field['id'] ] );
						break;
				}
				update_post_meta( $post_id, 'product_information_' . $field['id'], $_POST[ $field['id'] ] );
			} else if ( $field['type'] === 'checkbox' ) {
				update_post_meta( $post_id, 'product_information_' . $field['id'], '0' );
			}
		}
	}
}
new Rational_Meta_Box;
